Repository rogerluan/arkana, pull requests merged in 2023-12, with the labels that each got.

#51 Handle corner case of values that look like numbers but should be treated as strings
  lib/arkana/models/type.rb
  lib/arkana/templates/arkana_tests.swift.erb
  spec/fixtures/.env.fruitloops
  spec/fixtures/swift-tests.yml
  spec/models/type_spec.rb
Labels: bug

#54 Update Code Climate action version
  .github/workflows/push.yml
Labels: 🍉 Safe to Merge

#53 Add support to Android using Kotlin code generation
  .github/workflows/kotlin-tests.yml
  .gitignore
  README.md
  Rakefile
  docs/demo-used-to-gen-image.kt
  docs/demo-used-to-gen-image.swift
  docs/kotlin-demo.png
  docs/swift-demo.png
  lib/arkana.rb
  lib/arkana/config_parser.rb
  lib/arkana/helpers/kotlin_template_helper.rb
  lib/arkana/kotlin_code_generator.rb
  lib/arkana/models/arguments.rb
  lib/arkana/models/config.rb
  lib/arkana/models/template_arguments.rb
  lib/arkana/swift_code_generator.rb
  lib/arkana/templates/kotlin/arkana.kt.erb
  lib/arkana/templates/kotlin/arkana_protocol.kt.erb
  lib/arkana/templates/kotlin/arkana_tests.kt.erb
  lib/arkana/templates/kotlin/build.gradle.kts.erb
  lib/arkana/templates/swift/arkana.podspec.erb
  lib/arkana/templates/swift/arkana.swift.erb
  lib/arkana/templates/swift/arkana_protocol.swift.erb
  lib/arkana/templates/swift/arkana_tests.swift.erb
  lib/arkana/templates/swift/interfaces.podspec.erb
  lib/arkana/templates/swift/interfaces_package.swift.erb
  lib/arkana/templates/swift/interfaces_readme.erb
  lib/arkana/templates/swift/package.swift.erb
  spec/arkana_spec.rb
  spec/config_parser_spec.rb
  spec/fixtures/kotlin-tests.yml
  spec/fixtures/kotlin/build.gradle.kts
  spec/fixtures/kotlin/gradle/wrapper/gradle-wrapper.jar
  spec/fixtures/kotlin/gradle/wrapper/gradle-wrapper.properties
  spec/fixtures/kotlin/gradlew
  spec/fixtures/kotlin/gradlew.bat
  spec/kotlin_code_generator_spec.rb
  template.yml
Labels: approved, feature
